import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KnoWord",
  description: "Generated by create next app",

   //Metadatos PWA
  manifest: "/manifest.json",
  themeColor: "##0F172A",
  viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
